<a href="https://colab.research.google.com/github/valuedriven/dataanalysis/blob/master/exercicio_pandas_complementar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício

1. Abra o arquivo DiamondsPrices.csv
2. Determine qual o valor do diamante mais caro na tabela e quantos quilates (carat) ele tem
3. Determine a média e o desvio padrão dos preços dos diamantes
4. Determine qual o diamante mais caro para cada tipo de corte (cut)
5. Determine qual o diamante mais caro para cada tipo de cor (color)
6. Determine qual o diamante mais caro para cada tipo de claridade (clarity)
7. Admitindo que a forma do diamante seja a de um cone de base elíptica, crie uma coluna com o volume aproximado do diamante dado pela equação

$$ V = \frac{1}{3}\pi xyz $$

8. Faça um gráfico de pontos do preço do diamante em função dos quilates (carat) colorindo os pontos com uma cor para cada tipo de corte (cut). Você observa alguma relação entre essas variáveis?

9. Faça um gráfico de pontos do quilate (carat) em função do volume colorindo os pontos com uma cor para cada tipo de claridade (clarity). Você observa alguma relação entre essas variáveis?

Abra o arquivo DiamondsPrices.csv

In [1]:
import pandas as pd

df = pd.read_csv("DiamondsPrices.csv",index_col=0)
df

             cut color clarity  depth  table  price     x     y     z
carat
0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...          ...   ...     ...    ...    ...    ...   ...   ...   ...
0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 9 columns]

Determine qual o valor do diamante mais caro na tabela e quantos quilates (carat) ele tem