<a href="https://colab.research.google.com/github/valuedriven/dataanalysis/blob/master/exercicio_pandas_complementar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício Pandas Complementar

1. Abra o arquivo DiamondsPrices.csv
2. Determine qual o valor do diamante mais caro na tabela e quantos quilates (carat) ele tem
3. Determine a média e o desvio padrão dos preços dos diamantes
4. Determine qual o diamante mais caro para cada tipo de corte (cut)
5. Determine qual o diamante mais caro para cada tipo de cor (color)
6. Determine qual o diamante mais caro para cada tipo de claridade (clarity)
7. Admitindo que a forma do diamante seja a de um cone de base elíptica, crie uma coluna com o volume aproximado do diamante dado pela equação

$$ V = \frac{1}{3}\pi xyz $$

8. Faça um gráfico de pontos do preço do diamante em função dos quilates (carat) colorindo os pontos com uma cor para cada tipo de corte (cut). Você observa alguma relação entre essas variáveis?

9. Faça um gráfico de pontos do quilate (carat) em função do volume colorindo os pontos com uma cor para cada tipo de claridade (clarity). Você observa alguma relação entre essas variáveis?

Abra o arquivo DiamondsPrices.csv

In [59]:
import pandas as pd

df = pd.read_csv("DiamondsPrices.csv",index_col=0)
df

             cut color clarity  depth  table  price     x     y     z
carat
0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...          ...   ...     ...    ...    ...    ...   ...   ...   ...
0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 9 columns]

Determine qual o valor do diamante mais caro na tabela e quantos quilates (carat) ele tem

In [60]:
index_needed = df["price"].idxmax()
df.iloc[[index_needed]]

# alternativa
# df.query('price == price.max()')

        cut color clarity  depth  table  price     x     y     z
carat
0.23   Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

Determine a média e o desvio padrão dos preços dos diamantes

In [61]:
mean_price = df["price"].mean()
mean_price

3932.799721913237

In [62]:
std_price = df["price"].std(ddof=1)
std_price

3989.439738146379

Determine qual o diamante mais caro para cada tipo de corte (cut)

In [63]:
df.groupby(['cut']).max()

          color clarity  depth  table  price      x      y      z
cut
Fair          J    VVS2   79.0   95.0  18574  10.74  10.54   6.98
Good          J    VVS2   67.0   66.0  18788   9.44   9.38   5.79
Ideal         J    VVS2   66.7   63.0  18806   9.65  31.80   6.03
Premium       J    VVS2   63.0   62.0  18823  10.14  58.90   8.06
Very Good     J    VVS2   64.9   66.0  18818  10.01   9.94  31.80

Determine qual o diamante mais caro para cada tipo de cor (color)

In [64]:
df.groupby(['color']).max()

             cut clarity  depth  table  price      x      y      z
color
D      Very Good    VVS2   71.6   73.0  18693   9.42   9.34   6.27
E      Very Good    VVS2   79.0   73.0  18731   9.26  31.80  31.80
F      Very Good    VVS2   71.0   95.0  18791   9.24   9.13   5.73
G      Very Good    VVS2   72.9   76.0  18818   9.44   9.37   6.16
H      Very Good    VVS2   71.8   73.0  18803  10.00  58.90   8.06
I      Very Good    VVS2   71.3   70.0  18823  10.14  10.10   6.31
J      Very Good    VVS2   73.6   68.0  18710  10.74  10.54   6.98

Determine qual o diamante mais caro para cada tipo de claridade (clarity)

In [65]:
df.groupby(['clarity']).max()

               cut color  depth  table  price      x      y      z
clarity
I1       Very Good     J   78.2   67.0  18531  10.74  10.54   6.98
IF       Very Good     J   65.6   65.0  18806   8.49   8.49   5.20
SI1      Very Good     J   72.9   95.0  18818   8.90   8.87   5.49
SI2      Very Good     J   72.2   79.0  18804   9.51  58.90   8.06
VS1      Very Good     J   71.8   73.0  18795   8.83  31.80  31.80
VS2      Very Good     J   79.0   73.0  18823   9.66   9.63   6.03
VVS1     Very Good     J   67.6   68.0  18777   8.49   8.42   5.25
VVS2     Very Good     J   67.6   68.0  18768   8.18   8.17   5.11

Admitindo que a forma do diamante seja a de um cone de base elíptica, crie uma coluna com o volume aproximado do diamante dado pela equação

$$ V = \frac{1}{3}\pi xyz $$

In [90]:
import math

df['volume'] = [(math.pi*x*y*z)/3 for x,y,z in zip(df['x'], df['y'], df['z'])]
df

,cut,color,clarity,depth,table,price,x,y,z,volume
carat,,,,,,,,,,
0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,40.005072
0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,36.134448
0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,39.874021
0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,48.929866
0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,54.367617
...,...,...,...,...,...,...,...,...,...,...
0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,121.391140
0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,123.684686
0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,119.851475
0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,147.409936
0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,130.447770